### ISSUE TITLE
Update checks

### ISSUE THREAD

**Issue by cingeyedog** [rossengeorgiev/salt-security-backports#5]
Not sure if the following checks are correct:
check_CVE_2020_11651
check_CVE_2020_11652_read_token

Specifically it is checking if Salt has a timedout on that function call.

Tokens (localfs) wasnt introduced until 2018.3, so earlier versions should timeout (I think)

**Comment by rossengeorgiev** [comment]
The method doesn't exist, which will cause an exception on the salt master, and no reply. Meaning it is not patched. Otherwise, we get an empty reply. I intentionally did it that way to avoid giving away an easy to copy-paste example of exploiting the vulnerability.

The pre-2018 patches are slightly different in order to cover the `get_token` case. As far as I can tell from my tests, it works. I welcome people scrutinizing the patch in case I have overlooked something.
